version: "3.7"

services:
  tcc_api:
    image: tcc_api
    container_name: 'tcc_api'
    build:
      dockerfile: ./Dockerfile
      context: .
    restart: unless-stopped
    volumes:
      - .:/app/
      - /app/node_modules
      - ./logs:/app/logs
    networks: 
      - backend
    depends_on: 
      - tcc_db
    ports:
      - "3030:3030"
    env_file: 
      - .env
    environment:
      API_PORT: 3030
      BASE_URL: localhost
      DB_DIALECT: postgres
      DB_PORT: 5432
      DB_HOST: tcc_db
      DB_NAME: Tcc
      DB_USERNAME: postgres
      DB_PASSWORD: ${DB_PASSWORD}
    command: npm run start

  tcc_db:
    image: postgres
    container_name: 'tcc_db'
    restart: unless-stopped
    volumes:
      - ./config/database/init.sql:/data/application/init.sql
      - local_db_data:/var/lib/postgresql/data
    env_file: 
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: Tcc
    ports:
      - "5432:5432"
    networks: 
      - backend

  pg-admin:
    image: dpage/pgadmin4
    container_name: 'pgadmin4_tcc'
    restart: unless-stopped
    depends_on: 
      - tcc_db
    volumes: 
      - pgadmin-data:/var/lib/pgadmin
    networks: 
      - backend
    ports:
      - "5051:80"
    env_file: 
      - .env
    environment: 
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    
volumes:
  local_db_data:
  pgadmin-data:
  node_modules:
  logs:
  
networks:
  backend:
    driver: 'bridge'
  